# Uso la imagen oficial de Apache HTTP Server
FROM httpd:latest
 
# Copio el contenido del sitio web desde mi carpeta local "html" a la ruta del servicio Apache
COPY ./home/vardon/computonube/html/index.html
 
# Expuse el puerto 80 del contenedor (el puerto estándar de HTTP)
EXPOSE 8081:80
 

