services:
  apache:
    image: httpd:latest
    container_name: apache_contenedor
    ports:
      - "8081:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3307"
