services:
  web:
    build: .
    ports:
      - "8081:81"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo_db
      MYSQL_USER: vardon
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

